services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: myblogdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/code/static
      - ./media:/code/media
    depends_on:
      - web

  web:
    build: .
    volumes:
      - ./static:/code/static
      - ./media:/code/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:

