services:
  web:
    build: .
    command: gunicorn my_first_blog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev  # 환경 변수 파일 참조
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: do_it_django_db_user
      POSTGRES_PASSWORD: do_it_django_db_password
      POSTGRES_DB: do_it_django_dev
    restart: always

volumes:
  postgres_data:
